///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace web_testing_examples
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The C_Fill_Test_Form recording.
    /// </summary>
    [TestModule("190c882f-8743-472d-98c4-31007acf4b97", ModuleType.Recording, 1)]
    public partial class C_Fill_Test_Form : ITestModule
    {
        /// <summary>
        /// Holds an instance of the web_testing_examplesRepository repository.
        /// </summary>
        public static web_testing_examplesRepository repo = web_testing_examplesRepository.Instance;

        static C_Fill_Test_Form instance = new C_Fill_Test_Form();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public C_Fill_Test_Form()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static C_Fill_Test_Form Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'RanorexTestPage.Testname' at 8;9.", repo.RanorexTestPage.TestnameInfo, new RecordItemIndex(0));
            repo.RanorexTestPage.Testname.DoubleClick("8;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'name' with focus on 'RanorexTestPage.Testname'.", repo.RanorexTestPage.TestnameInfo, new RecordItemIndex(1));
            repo.RanorexTestPage.Testname.PressKeys("name");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'RanorexTestPage.Testemail' at 14;6.", repo.RanorexTestPage.TestemailInfo, new RecordItemIndex(2));
            repo.RanorexTestPage.Testemail.DoubleClick("14;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'email' with focus on 'RanorexTestPage.Testemail'.", repo.RanorexTestPage.TestemailInfo, new RecordItemIndex(3));
            repo.RanorexTestPage.Testemail.PressKeys("email");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RanorexTestPage.Testdate' at 76;7.", repo.RanorexTestPage.TestdateInfo, new RecordItemIndex(4));
            repo.RanorexTestPage.Testdate.Click("76;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RanorexTestPage.ThuApr13th2017' at 10;13.", repo.RanorexTestPage.ThuApr13th2017Info, new RecordItemIndex(5));
            repo.RanorexTestPage.ThuApr13th2017.Click("10;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RanorexTestPage.OptionTagRed' at 10;7.", repo.RanorexTestPage.OptionTagRedInfo, new RecordItemIndex(6));
            repo.RanorexTestPage.OptionTagRed.Click("10;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}' with focus on 'RanorexTestPage.Testmultiple'.", repo.RanorexTestPage.TestmultipleInfo, new RecordItemIndex(7));
            repo.RanorexTestPage.Testmultiple.PressKeys("{LControlKey down}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RanorexTestPage.Blue' at 23;11.", repo.RanorexTestPage.BlueInfo, new RecordItemIndex(8));
            repo.RanorexTestPage.Blue.Click("23;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RanorexTestPage.Gray' at 21;7.", repo.RanorexTestPage.GrayInfo, new RecordItemIndex(9));
            repo.RanorexTestPage.Gray.Click("21;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey up}' with focus on 'RanorexTestPage.Testmultiple'.", repo.RanorexTestPage.TestmultipleInfo, new RecordItemIndex(10));
            repo.RanorexTestPage.Testmultiple.PressKeys("{LControlKey up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RanorexTestPage.Submit' at Center.", repo.RanorexTestPage.SubmitInfo, new RecordItemIndex(11));
            repo.RanorexTestPage.Submit.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
