///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace web_testing_examples
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The D_Check_value recording.
    /// </summary>
    [TestModule("3781234b-0d5d-43ce-921d-b55563d3c1ac", ModuleType.Recording, 1)]
    public partial class D_Check_value : ITestModule
    {
        /// <summary>
        /// Holds an instance of the web_testing_examplesRepository repository.
        /// </summary>
        public static web_testing_examplesRepository repo = web_testing_examplesRepository.Instance;

        static D_Check_value instance = new D_Check_value();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public D_Check_value()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static D_Check_value Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Array\n(\n    [testname] => name\n    [testemail] => email\n    [testdate] => 13/04/2017\n    [testcolor] => green\n    [testmultiple] => Array\n        (\n            [0] => blue\n            [1] => red\n            [2] => gray\n        )\n\n)\n') on item 'RanorexTestPage.ArrayTestnameEqUserName'.", repo.RanorexTestPage.ArrayTestnameEqUserNameInfo, new RecordItemIndex(0));
            Validate.Attribute(repo.RanorexTestPage.ArrayTestnameEqUserNameInfo, "InnerText", "Array\n(\n    [testname] => name\n    [testemail] => email\n    [testdate] => 13/04/2017\n    [testcolor] => green\n    [testmultiple] => Array\n        (\n            [0] => blue\n            [1] => red\n            [2] => gray\n        )\n\n)\n");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WwwRanorexComWebTestingExamplesFor.IntermediateD3DWindow' at 18;57.", repo.WwwRanorexComWebTestingExamplesFor.IntermediateD3DWindowInfo, new RecordItemIndex(1));
            repo.WwwRanorexComWebTestingExamplesFor.IntermediateD3DWindow.Click("18;57");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
