///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace web_testing_examples
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The E_Fill_Test_form_with_Ajax recording.
    /// </summary>
    [TestModule("c674ffe9-249b-436b-8ae0-d59f9d650269", ModuleType.Recording, 1)]
    public partial class E_Fill_Test_form_with_Ajax : ITestModule
    {
        /// <summary>
        /// Holds an instance of the web_testing_examplesRepository repository.
        /// </summary>
        public static web_testing_examplesRepository repo = web_testing_examplesRepository.Instance;

        static E_Fill_Test_form_with_Ajax instance = new E_Fill_Test_form_with_Ajax();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public E_Fill_Test_form_with_Ajax()
        {
            Variable1 = "1";
            Variable2 = "2";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static E_Fill_Test_form_with_Ajax Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable Variable1.
        /// </summary>
        [TestVariable("84d9cf89-d39c-4053-ac68-1b2b755d8f33")]
        public string Variable1
        {
            get { return repo.Variable1; }
            set { repo.Variable1 = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Variable2.
        /// </summary>
        [TestVariable("fcf9ef0d-d4db-4d5f-8663-7fffd23625ed")]
        public string Variable2
        {
            get { return repo.Variable2; }
            set { repo.Variable2 = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'RanorexTestPage.Value1' at 9;10.", repo.RanorexTestPage.Value1Info, new RecordItemIndex(0));
            repo.RanorexTestPage.Value1.DoubleClick("9;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Variable1' with focus on 'RanorexTestPage.Value1'.", repo.RanorexTestPage.Value1Info, new RecordItemIndex(1));
            repo.RanorexTestPage.Value1.PressKeys(Variable1);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'RanorexTestPage.Value2' at 27;8.", repo.RanorexTestPage.Value2Info, new RecordItemIndex(2));
            repo.RanorexTestPage.Value2.DoubleClick("27;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Variable2' with focus on 'RanorexTestPage.Value2'.", repo.RanorexTestPage.Value2Info, new RecordItemIndex(3));
            repo.RanorexTestPage.Value2.PressKeys(Variable2);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RanorexTestPage.SubmitAjax' at 38;7.", repo.RanorexTestPage.SubmitAjaxInfo, new RecordItemIndex(4));
            repo.RanorexTestPage.SubmitAjax.Click("38;7");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
