///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace web_testing_examples
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Repository1 element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
    [RepositoryFolder("31d089f6-6729-4dd6-a354-ccd6cfe34811")]
    public partial class Repository1 : RepoGenBaseFolder
    {
        static Repository1 instance = new Repository1();
        Repository1Folders.WwwRanorexComWebTestingExamplesForAppFolder _wwwranorexcomwebtestingexamplesfor;
        Repository1Folders.RanorexTestPageAppFolder _ranorextestpage;

        /// <summary>
        /// Gets the singleton class instance representing the Repository1 element repository.
        /// </summary>
        [RepositoryFolder("31d089f6-6729-4dd6-a354-ccd6cfe34811")]
        public static Repository1 Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Repository1() 
            : base("Repository1", "/", null, 0, false, "31d089f6-6729-4dd6-a354-ccd6cfe34811", ".\\RepositoryImages\\Repository131d089f6.rximgres")
        {
            _wwwranorexcomwebtestingexamplesfor = new Repository1Folders.WwwRanorexComWebTestingExamplesForAppFolder(this);
            _ranorextestpage = new Repository1Folders.RanorexTestPageAppFolder(this);
        }

#region Variables

        string _NewVariable = "11";

        /// <summary>
        /// Gets or sets the value of variable NewVariable.
        /// </summary>
        [TestVariable("d87f2a2b-36a9-4526-8986-02e598108a26")]
        public string NewVariable
        {
            get { return _NewVariable; }
            set { _NewVariable = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("31d089f6-6729-4dd6-a354-ccd6cfe34811")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The WwwRanorexComWebTestingExamplesFor folder.
        /// </summary>
        [RepositoryFolder("87dbc312-35e1-4661-aa55-6779ce17dc87")]
        public virtual Repository1Folders.WwwRanorexComWebTestingExamplesForAppFolder WwwRanorexComWebTestingExamplesFor
        {
            get { return _wwwranorexcomwebtestingexamplesfor; }
        }

        /// <summary>
        /// The RanorexTestPage folder.
        /// </summary>
        [RepositoryFolder("2a068277-b3ae-4cd2-84eb-afcdba62e38a")]
        public virtual Repository1Folders.RanorexTestPageAppFolder RanorexTestPage
        {
            get { return _ranorextestpage; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
    public partial class Repository1Folders
    {
        /// <summary>
        /// The WwwRanorexComWebTestingExamplesForAppFolder folder.
        /// </summary>
        [RepositoryFolder("87dbc312-35e1-4661-aa55-6779ce17dc87")]
        public partial class WwwRanorexComWebTestingExamplesForAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _intermediated3dwindowInfo;

            /// <summary>
            /// Creates a new WwwRanorexComWebTestingExamplesFor  folder.
            /// </summary>
            public WwwRanorexComWebTestingExamplesForAppFolder(RepoGenBaseFolder parentFolder) :
                    base("WwwRanorexComWebTestingExamplesFor", "/form[@title~'^www\\.ranorex\\.com/web-testi']", parentFolder, 30000, null, true, "87dbc312-35e1-4661-aa55-6779ce17dc87", "")
            {
                _intermediated3dwindowInfo = new RepoItemInfo(this, "IntermediateD3DWindow", "element[@class='Intermediate D3D Window']", 30000, null, "7426afea-a6a1-4e36-bdca-839b074f5a2f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("87dbc312-35e1-4661-aa55-6779ce17dc87")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("87dbc312-35e1-4661-aa55-6779ce17dc87")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The IntermediateD3DWindow item.
            /// </summary>
            [RepositoryItem("7426afea-a6a1-4e36-bdca-839b074f5a2f")]
            public virtual Ranorex.Unknown IntermediateD3DWindow
            {
                get
                {
                    return _intermediated3dwindowInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The IntermediateD3DWindow item info.
            /// </summary>
            [RepositoryItemInfo("7426afea-a6a1-4e36-bdca-839b074f5a2f")]
            public virtual RepoItemInfo IntermediateD3DWindowInfo
            {
                get
                {
                    return _intermediated3dwindowInfo;
                }
            }
        }

        /// <summary>
        /// The RanorexTestPageAppFolder folder.
        /// </summary>
        [RepositoryFolder("2a068277-b3ae-4cd2-84eb-afcdba62e38a")]
        public partial class RanorexTestPageAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _menu1Info;
            RepoItemInfo _subitem2Info;
            RepoItemInfo _testnameInfo;
            RepoItemInfo _testemailInfo;
            RepoItemInfo _testdateInfo;
            RepoItemInfo _thuapr13th2017Info;
            RepoItemInfo _optiontagredInfo;
            RepoItemInfo _testmultipleInfo;
            RepoItemInfo _blueInfo;
            RepoItemInfo _grayInfo;
            RepoItemInfo _submitInfo;
            RepoItemInfo _arraytestnameequsernameInfo;
            RepoItemInfo _value1Info;
            RepoItemInfo _value2Info;
            RepoItemInfo _submitajaxInfo;
            RepoItemInfo _ajaxoutInfo;
            RepoItemInfo _arrayvalue1eq1value2eInfo;

            /// <summary>
            /// Creates a new RanorexTestPage  folder.
            /// </summary>
            public RanorexTestPageAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RanorexTestPage", "/dom[@domain='www.ranorex.com']", parentFolder, 30000, null, false, "2a068277-b3ae-4cd2-84eb-afcdba62e38a", "")
            {
                _menu1Info = new RepoItemInfo(this, "Menu1", ".//ul[#'nav']/?/?/a[@innertext='Menu 1']", 30000, null, "680c6933-e812-4a4a-ad58-88f96ef57688");
                _subitem2Info = new RepoItemInfo(this, "Subitem2", ".//ul[#'nav']/?/?/ul/?/?/a[@innertext='Subitem 2']", 30000, null, "ba0fd282-2947-49c3-b076-daa72c110ead");
                _testnameInfo = new RepoItemInfo(this, "Testname", ".//input[#'testname']", 30000, null, "db8821c0-9024-42c9-8fb0-ecb9895a2629");
                _testemailInfo = new RepoItemInfo(this, "Testemail", ".//input[#'testemail']", 30000, null, "c45eb6e6-ca93-4f4d-9ced-91419682eeca");
                _testdateInfo = new RepoItemInfo(this, "Testdate", ".//input[#'testdate']", 30000, null, "4715ead9-d768-4001-8540-6b5c0e015045");
                _thuapr13th2017Info = new RepoItemInfo(this, "ThuApr13th2017", "body/div[2]/?/?/table/tbody/tr[4]/td[@title='Thu Apr 13th 2017']", 30000, null, "5f4a06e5-e848-44a3-9952-ca2d7781dd4d");
                _optiontagredInfo = new RepoItemInfo(this, "OptionTagRed", ".//select[#'testmultiple']/option[@value='red']", 30000, null, "5fdc7c76-a2f2-4266-88cb-0fb735fd793f");
                _testmultipleInfo = new RepoItemInfo(this, "Testmultiple", ".//select[#'testmultiple']", 30000, null, "6c4d1fd9-3a8c-445c-96a8-5c5a74788847");
                _blueInfo = new RepoItemInfo(this, "Blue", ".//select[#'testmultiple']/option[@value='blue']", 30000, null, "664138a9-9927-4adc-b7ff-c772e12ef40c");
                _grayInfo = new RepoItemInfo(this, "Gray", ".//select[#'testmultiple']/option[@value='gray']", 30000, null, "5450d600-3bbe-408d-959b-55869d0d3866");
                _submitInfo = new RepoItemInfo(this, "Submit", ".//input[#'submit']", 30000, null, "af2b6205-bf4f-46f3-8ed1-f459f0fab4eb");
                _arraytestnameequsernameInfo = new RepoItemInfo(this, "ArrayTestnameEqUserName", "?/?/pre[@innertext~'^Array\\(\\ \\ \\ \\ \\[testname]\\ =>']", 30000, null, "9c2c3cbf-c126-4135-9f8a-354ee5a96a75");
                _value1Info = new RepoItemInfo(this, "Value1", ".//input[#'value1']", 30000, null, "46eb1046-9af8-47e5-92d3-5de08dc826c4");
                _value2Info = new RepoItemInfo(this, "Value2", ".//input[#'value2']", 30000, null, "117693eb-4df4-49d6-8633-f860560aee97");
                _submitajaxInfo = new RepoItemInfo(this, "SubmitAjax", ".//input[#'submit-ajax']", 30000, null, "10cb4e7a-b7ee-4230-89db-03ffd8f326f9");
                _ajaxoutInfo = new RepoItemInfo(this, "AjaxOut", ".//div[#'ajax_out']", 30000, null, "9faaea8d-0096-4a3a-80df-fe0470ddc702");
                _arrayvalue1eq1value2eInfo = new RepoItemInfo(this, "ArrayValue1Eq1Value2E", ".//div[#'ajax_out']/pre[@innertext~'^Array\\(\\ \\ \\ \\ \\[value1]\\ =>\\ 1']", 30000, null, "58a7c468-1d45-48b8-b2ad-08e332a3345d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2a068277-b3ae-4cd2-84eb-afcdba62e38a")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2a068277-b3ae-4cd2-84eb-afcdba62e38a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Menu1 item.
            /// </summary>
            [RepositoryItem("680c6933-e812-4a4a-ad58-88f96ef57688")]
            public virtual Ranorex.ATag Menu1
            {
                get
                {
                    return _menu1Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Menu1 item info.
            /// </summary>
            [RepositoryItemInfo("680c6933-e812-4a4a-ad58-88f96ef57688")]
            public virtual RepoItemInfo Menu1Info
            {
                get
                {
                    return _menu1Info;
                }
            }

            /// <summary>
            /// The Subitem2 item.
            /// </summary>
            [RepositoryItem("ba0fd282-2947-49c3-b076-daa72c110ead")]
            public virtual Ranorex.ATag Subitem2
            {
                get
                {
                    return _subitem2Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Subitem2 item info.
            /// </summary>
            [RepositoryItemInfo("ba0fd282-2947-49c3-b076-daa72c110ead")]
            public virtual RepoItemInfo Subitem2Info
            {
                get
                {
                    return _subitem2Info;
                }
            }

            /// <summary>
            /// The Testname item.
            /// </summary>
            [RepositoryItem("db8821c0-9024-42c9-8fb0-ecb9895a2629")]
            public virtual Ranorex.InputTag Testname
            {
                get
                {
                    return _testnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Testname item info.
            /// </summary>
            [RepositoryItemInfo("db8821c0-9024-42c9-8fb0-ecb9895a2629")]
            public virtual RepoItemInfo TestnameInfo
            {
                get
                {
                    return _testnameInfo;
                }
            }

            /// <summary>
            /// The Testemail item.
            /// </summary>
            [RepositoryItem("c45eb6e6-ca93-4f4d-9ced-91419682eeca")]
            public virtual Ranorex.InputTag Testemail
            {
                get
                {
                    return _testemailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Testemail item info.
            /// </summary>
            [RepositoryItemInfo("c45eb6e6-ca93-4f4d-9ced-91419682eeca")]
            public virtual RepoItemInfo TestemailInfo
            {
                get
                {
                    return _testemailInfo;
                }
            }

            /// <summary>
            /// The Testdate item.
            /// </summary>
            [RepositoryItem("4715ead9-d768-4001-8540-6b5c0e015045")]
            public virtual Ranorex.InputTag Testdate
            {
                get
                {
                    return _testdateInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Testdate item info.
            /// </summary>
            [RepositoryItemInfo("4715ead9-d768-4001-8540-6b5c0e015045")]
            public virtual RepoItemInfo TestdateInfo
            {
                get
                {
                    return _testdateInfo;
                }
            }

            /// <summary>
            /// The ThuApr13th2017 item.
            /// </summary>
            [RepositoryItem("5f4a06e5-e848-44a3-9952-ca2d7781dd4d")]
            public virtual Ranorex.TdTag ThuApr13th2017
            {
                get
                {
                    return _thuapr13th2017Info.CreateAdapter<Ranorex.TdTag>(true);
                }
            }

            /// <summary>
            /// The ThuApr13th2017 item info.
            /// </summary>
            [RepositoryItemInfo("5f4a06e5-e848-44a3-9952-ca2d7781dd4d")]
            public virtual RepoItemInfo ThuApr13th2017Info
            {
                get
                {
                    return _thuapr13th2017Info;
                }
            }

            /// <summary>
            /// The OptionTagRed item.
            /// </summary>
            [RepositoryItem("5fdc7c76-a2f2-4266-88cb-0fb735fd793f")]
            public virtual Ranorex.OptionTag OptionTagRed
            {
                get
                {
                    return _optiontagredInfo.CreateAdapter<Ranorex.OptionTag>(true);
                }
            }

            /// <summary>
            /// The OptionTagRed item info.
            /// </summary>
            [RepositoryItemInfo("5fdc7c76-a2f2-4266-88cb-0fb735fd793f")]
            public virtual RepoItemInfo OptionTagRedInfo
            {
                get
                {
                    return _optiontagredInfo;
                }
            }

            /// <summary>
            /// The Testmultiple item.
            /// </summary>
            [RepositoryItem("6c4d1fd9-3a8c-445c-96a8-5c5a74788847")]
            public virtual Ranorex.SelectTag Testmultiple
            {
                get
                {
                    return _testmultipleInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The Testmultiple item info.
            /// </summary>
            [RepositoryItemInfo("6c4d1fd9-3a8c-445c-96a8-5c5a74788847")]
            public virtual RepoItemInfo TestmultipleInfo
            {
                get
                {
                    return _testmultipleInfo;
                }
            }

            /// <summary>
            /// The Blue item.
            /// </summary>
            [RepositoryItem("664138a9-9927-4adc-b7ff-c772e12ef40c")]
            public virtual Ranorex.OptionTag Blue
            {
                get
                {
                    return _blueInfo.CreateAdapter<Ranorex.OptionTag>(true);
                }
            }

            /// <summary>
            /// The Blue item info.
            /// </summary>
            [RepositoryItemInfo("664138a9-9927-4adc-b7ff-c772e12ef40c")]
            public virtual RepoItemInfo BlueInfo
            {
                get
                {
                    return _blueInfo;
                }
            }

            /// <summary>
            /// The Gray item.
            /// </summary>
            [RepositoryItem("5450d600-3bbe-408d-959b-55869d0d3866")]
            public virtual Ranorex.OptionTag Gray
            {
                get
                {
                    return _grayInfo.CreateAdapter<Ranorex.OptionTag>(true);
                }
            }

            /// <summary>
            /// The Gray item info.
            /// </summary>
            [RepositoryItemInfo("5450d600-3bbe-408d-959b-55869d0d3866")]
            public virtual RepoItemInfo GrayInfo
            {
                get
                {
                    return _grayInfo;
                }
            }

            /// <summary>
            /// The Submit item.
            /// </summary>
            [RepositoryItem("af2b6205-bf4f-46f3-8ed1-f459f0fab4eb")]
            public virtual Ranorex.InputTag Submit
            {
                get
                {
                    return _submitInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Submit item info.
            /// </summary>
            [RepositoryItemInfo("af2b6205-bf4f-46f3-8ed1-f459f0fab4eb")]
            public virtual RepoItemInfo SubmitInfo
            {
                get
                {
                    return _submitInfo;
                }
            }

            /// <summary>
            /// The ArrayTestnameEqUserName item.
            /// </summary>
            [RepositoryItem("9c2c3cbf-c126-4135-9f8a-354ee5a96a75")]
            public virtual Ranorex.PreTag ArrayTestnameEqUserName
            {
                get
                {
                    return _arraytestnameequsernameInfo.CreateAdapter<Ranorex.PreTag>(true);
                }
            }

            /// <summary>
            /// The ArrayTestnameEqUserName item info.
            /// </summary>
            [RepositoryItemInfo("9c2c3cbf-c126-4135-9f8a-354ee5a96a75")]
            public virtual RepoItemInfo ArrayTestnameEqUserNameInfo
            {
                get
                {
                    return _arraytestnameequsernameInfo;
                }
            }

            /// <summary>
            /// The Value1 item.
            /// </summary>
            [RepositoryItem("46eb1046-9af8-47e5-92d3-5de08dc826c4")]
            public virtual Ranorex.InputTag Value1
            {
                get
                {
                    return _value1Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Value1 item info.
            /// </summary>
            [RepositoryItemInfo("46eb1046-9af8-47e5-92d3-5de08dc826c4")]
            public virtual RepoItemInfo Value1Info
            {
                get
                {
                    return _value1Info;
                }
            }

            /// <summary>
            /// The Value2 item.
            /// </summary>
            [RepositoryItem("117693eb-4df4-49d6-8633-f860560aee97")]
            public virtual Ranorex.InputTag Value2
            {
                get
                {
                    return _value2Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Value2 item info.
            /// </summary>
            [RepositoryItemInfo("117693eb-4df4-49d6-8633-f860560aee97")]
            public virtual RepoItemInfo Value2Info
            {
                get
                {
                    return _value2Info;
                }
            }

            /// <summary>
            /// The SubmitAjax item.
            /// </summary>
            [RepositoryItem("10cb4e7a-b7ee-4230-89db-03ffd8f326f9")]
            public virtual Ranorex.InputTag SubmitAjax
            {
                get
                {
                    return _submitajaxInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The SubmitAjax item info.
            /// </summary>
            [RepositoryItemInfo("10cb4e7a-b7ee-4230-89db-03ffd8f326f9")]
            public virtual RepoItemInfo SubmitAjaxInfo
            {
                get
                {
                    return _submitajaxInfo;
                }
            }

            /// <summary>
            /// The AjaxOut item.
            /// </summary>
            [RepositoryItem("9faaea8d-0096-4a3a-80df-fe0470ddc702")]
            public virtual Ranorex.DivTag AjaxOut
            {
                get
                {
                    return _ajaxoutInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The AjaxOut item info.
            /// </summary>
            [RepositoryItemInfo("9faaea8d-0096-4a3a-80df-fe0470ddc702")]
            public virtual RepoItemInfo AjaxOutInfo
            {
                get
                {
                    return _ajaxoutInfo;
                }
            }

            /// <summary>
            /// The ArrayValue1Eq1Value2E item.
            /// </summary>
            [RepositoryItem("58a7c468-1d45-48b8-b2ad-08e332a3345d")]
            public virtual Ranorex.PreTag ArrayValue1Eq1Value2E
            {
                get
                {
                    return _arrayvalue1eq1value2eInfo.CreateAdapter<Ranorex.PreTag>(true);
                }
            }

            /// <summary>
            /// The ArrayValue1Eq1Value2E item info.
            /// </summary>
            [RepositoryItemInfo("58a7c468-1d45-48b8-b2ad-08e332a3345d")]
            public virtual RepoItemInfo ArrayValue1Eq1Value2EInfo
            {
                get
                {
                    return _arrayvalue1eq1value2eInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}