///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace web_testing_examples
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the web_testing_examplesRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
    [RepositoryFolder("71c46e42-d3c5-4a80-9435-9c648c72ebb0")]
    public partial class web_testing_examplesRepository : RepoGenBaseFolder
    {
        static web_testing_examplesRepository instance = new web_testing_examplesRepository();
        web_testing_examplesRepositoryFolders.RanorexTestPageAppFolder _ranorextestpage;
        web_testing_examplesRepositoryFolders.WwwRanorexComWebTestingExamplesForAppFolder _wwwranorexcomwebtestingexamplesfor;

        /// <summary>
        /// Gets the singleton class instance representing the web_testing_examplesRepository element repository.
        /// </summary>
        [RepositoryFolder("71c46e42-d3c5-4a80-9435-9c648c72ebb0")]
        public static web_testing_examplesRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public web_testing_examplesRepository() 
            : base("web_testing_examplesRepository", "/", null, 0, false, "71c46e42-d3c5-4a80-9435-9c648c72ebb0", ".\\RepositoryImages\\web_testing_examplesRepository71c46e42.rximgres")
        {
            _ranorextestpage = new web_testing_examplesRepositoryFolders.RanorexTestPageAppFolder(this);
            _wwwranorexcomwebtestingexamplesfor = new web_testing_examplesRepositoryFolders.WwwRanorexComWebTestingExamplesForAppFolder(this);
        }

#region Variables

        string _Variable1 = "1";

        /// <summary>
        /// Gets or sets the value of variable Variable1.
        /// </summary>
        [TestVariable("de9de425-7b57-4678-8ef8-c7b937baef4f")]
        public string Variable1
        {
            get { return _Variable1; }
            set { _Variable1 = value; }
        }

        string _Variable2 = "2";

        /// <summary>
        /// Gets or sets the value of variable Variable2.
        /// </summary>
        [TestVariable("fdf372bb-95e4-418b-b42e-29521b9ecc13")]
        public string Variable2
        {
            get { return _Variable2; }
            set { _Variable2 = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("71c46e42-d3c5-4a80-9435-9c648c72ebb0")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The RanorexTestPage folder.
        /// </summary>
        [RepositoryFolder("58ff8a75-6faa-4ca4-9f66-b21d9f6edeb4")]
        public virtual web_testing_examplesRepositoryFolders.RanorexTestPageAppFolder RanorexTestPage
        {
            get { return _ranorextestpage; }
        }

        /// <summary>
        /// The WwwRanorexComWebTestingExamplesFor folder.
        /// </summary>
        [RepositoryFolder("37a0fe02-ff1b-45fb-8521-e27c972e818b")]
        public virtual web_testing_examplesRepositoryFolders.WwwRanorexComWebTestingExamplesForAppFolder WwwRanorexComWebTestingExamplesFor
        {
            get { return _wwwranorexcomwebtestingexamplesfor; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
    public partial class web_testing_examplesRepositoryFolders
    {
        /// <summary>
        /// The RanorexTestPageAppFolder folder.
        /// </summary>
        [RepositoryFolder("58ff8a75-6faa-4ca4-9f66-b21d9f6edeb4")]
        public partial class RanorexTestPageAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _menu1Info;
            RepoItemInfo _subitem2Info;
            RepoItemInfo _testnameInfo;
            RepoItemInfo _testemailInfo;
            RepoItemInfo _somebodytagInfo;
            RepoItemInfo _calendarInfo;
            RepoItemInfo _thuapr13th2017Info;
            RepoItemInfo _blueInfo;
            RepoItemInfo _testmultipleInfo;
            RepoItemInfo _optiontagredInfo;
            RepoItemInfo _grayInfo;
            RepoItemInfo _submitInfo;
            RepoItemInfo _arraytestnameequsernameInfo;
            RepoItemInfo _greenInfo;
            RepoItemInfo _testdateInfo;
            RepoItemInfo _value1Info;
            RepoItemInfo _value2Info;
            RepoItemInfo _submitajaxInfo;
            RepoItemInfo _ajaxoutInfo;
            RepoItemInfo _testformInfo;
            RepoItemInfo _arrayvalue1eq1value2e1Info;
            RepoItemInfo _arrayvalue1eq1value2eInfo;

            /// <summary>
            /// Creates a new RanorexTestPage  folder.
            /// </summary>
            public RanorexTestPageAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RanorexTestPage", "/dom[@domain='www.ranorex.com']", parentFolder, 30000, null, false, "58ff8a75-6faa-4ca4-9f66-b21d9f6edeb4", "")
            {
                _menu1Info = new RepoItemInfo(this, "Menu1", ".//ul[#'nav']/?/?/a[@innertext='Menu 1']", 30000, null, "fbec5051-2675-4487-b29a-8811f2288d32");
                _subitem2Info = new RepoItemInfo(this, "Subitem2", ".//ul[#'nav']/?/?/ul/?/?/a[@innertext='Subitem 2']", 30000, null, "d423d4f7-188c-4407-90ed-64cdd4582830");
                _testnameInfo = new RepoItemInfo(this, "Testname", ".//input[#'testname']", 30000, null, "4d415a2c-c213-4b7e-b358-95cbd5c2f020");
                _testemailInfo = new RepoItemInfo(this, "Testemail", ".//input[#'testemail']", 30000, null, "e5578bca-a215-4f9a-ad68-1e1a82b523d7");
                _somebodytagInfo = new RepoItemInfo(this, "SomeBodyTag", "body", 30000, null, "53261d83-8c87-4b05-8546-89b805b825d8");
                _calendarInfo = new RepoItemInfo(this, "Calendar", ".//form[#'testform']/?/?/ol/?/?/button", 30000, null, "9ef39c80-0c5c-4f2c-bbd9-6083679df5a0");
                _thuapr13th2017Info = new RepoItemInfo(this, "ThuApr13th2017", "body/div[2]/?/?/table/tbody/tr[4]/td[@title='Thu Apr 13th 2017']", 30000, null, "beb20ba8-fc45-40c6-8f99-14c305b2c013");
                _blueInfo = new RepoItemInfo(this, "Blue", ".//select[#'testmultiple']/option[@value='blue']", 30000, null, "f3657d7f-2e18-4e1d-a99e-e89418632647");
                _testmultipleInfo = new RepoItemInfo(this, "Testmultiple", ".//select[#'testmultiple']", 30000, null, "1fb7c4e1-48a2-44ee-8e82-ae643da4f873");
                _optiontagredInfo = new RepoItemInfo(this, "OptionTagRed", ".//select[#'testmultiple']/option[@value='red']", 30000, null, "2546f8cf-8984-4493-a168-a51311f3902c");
                _grayInfo = new RepoItemInfo(this, "Gray", ".//select[#'testmultiple']/option[@value='gray']", 30000, null, "552323d2-146f-4ea5-8041-767126f63bdc");
                _submitInfo = new RepoItemInfo(this, "Submit", ".//input[#'submit']", 30000, null, "32c9a657-0172-44ee-87e8-6af62dca8ebb");
                _arraytestnameequsernameInfo = new RepoItemInfo(this, "ArrayTestnameEqUserName", "?/?/pre[@innertext~'^Array\\(\\ \\ \\ \\ \\[testname]\\ =>']", 30000, null, "1763f1f6-1a6e-42e0-830f-36d111ebbee4");
                _greenInfo = new RepoItemInfo(this, "Green", ".//select[#'testmultiple']/option[@value='green']", 30000, null, "0f1eb2c6-a31d-43cc-bc1f-6123f60cc674");
                _testdateInfo = new RepoItemInfo(this, "Testdate", ".//input[#'testdate']", 30000, null, "baea20b2-f16d-4ae6-a57e-4905cd89aecb");
                _value1Info = new RepoItemInfo(this, "Value1", ".//input[#'value1']", 30000, null, "c07fc419-d765-48f0-95a3-75bab194f444");
                _value2Info = new RepoItemInfo(this, "Value2", ".//input[#'value2']", 30000, null, "9609b147-5f7d-4ea0-b3e2-fa14e69f8d04");
                _submitajaxInfo = new RepoItemInfo(this, "SubmitAjax", ".//input[#'submit-ajax']", 30000, null, "754638dc-0bc4-41cd-8021-c2808f9ff537");
                _ajaxoutInfo = new RepoItemInfo(this, "AjaxOut", ".//div[#'ajax_out']", 30000, null, "f889e3d0-b7a2-4667-b743-5464c457b30a");
                _testformInfo = new RepoItemInfo(this, "Testform", ".//form[#'testform']", 30000, null, "33e1ee9f-2da8-462e-bf63-85e4efa69759");
                _arrayvalue1eq1value2e1Info = new RepoItemInfo(this, "ArrayValue1Eq1Value2E1", ".//div[#'ajax_out']/pre[@innertext~'Array(    [value1] => 1    [value2] => 2    [color2] => green)']", 30000, null, "c90bb30e-4c26-4420-ab27-b90608704770");
                _arrayvalue1eq1value2eInfo = new RepoItemInfo(this, "ArrayValue1Eq1Value2E", ".//div[#'ajax_out']/pre[@innertext~'^Array\\(\\ \\ \\ \\ \\[value1]\\ =>\\ 1']", 30000, null, "8582ee05-09da-45e8-86e5-7489a314bedf");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("58ff8a75-6faa-4ca4-9f66-b21d9f6edeb4")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("58ff8a75-6faa-4ca4-9f66-b21d9f6edeb4")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Menu1 item.
            /// </summary>
            [RepositoryItem("fbec5051-2675-4487-b29a-8811f2288d32")]
            public virtual Ranorex.ATag Menu1
            {
                get
                {
                    return _menu1Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Menu1 item info.
            /// </summary>
            [RepositoryItemInfo("fbec5051-2675-4487-b29a-8811f2288d32")]
            public virtual RepoItemInfo Menu1Info
            {
                get
                {
                    return _menu1Info;
                }
            }

            /// <summary>
            /// The Subitem2 item.
            /// </summary>
            [RepositoryItem("d423d4f7-188c-4407-90ed-64cdd4582830")]
            public virtual Ranorex.ATag Subitem2
            {
                get
                {
                    return _subitem2Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Subitem2 item info.
            /// </summary>
            [RepositoryItemInfo("d423d4f7-188c-4407-90ed-64cdd4582830")]
            public virtual RepoItemInfo Subitem2Info
            {
                get
                {
                    return _subitem2Info;
                }
            }

            /// <summary>
            /// The Testname item.
            /// </summary>
            [RepositoryItem("4d415a2c-c213-4b7e-b358-95cbd5c2f020")]
            public virtual Ranorex.InputTag Testname
            {
                get
                {
                    return _testnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Testname item info.
            /// </summary>
            [RepositoryItemInfo("4d415a2c-c213-4b7e-b358-95cbd5c2f020")]
            public virtual RepoItemInfo TestnameInfo
            {
                get
                {
                    return _testnameInfo;
                }
            }

            /// <summary>
            /// The Testemail item.
            /// </summary>
            [RepositoryItem("e5578bca-a215-4f9a-ad68-1e1a82b523d7")]
            public virtual Ranorex.InputTag Testemail
            {
                get
                {
                    return _testemailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Testemail item info.
            /// </summary>
            [RepositoryItemInfo("e5578bca-a215-4f9a-ad68-1e1a82b523d7")]
            public virtual RepoItemInfo TestemailInfo
            {
                get
                {
                    return _testemailInfo;
                }
            }

            /// <summary>
            /// The SomeBodyTag item.
            /// </summary>
            [RepositoryItem("53261d83-8c87-4b05-8546-89b805b825d8")]
            public virtual Ranorex.BodyTag SomeBodyTag
            {
                get
                {
                    return _somebodytagInfo.CreateAdapter<Ranorex.BodyTag>(true);
                }
            }

            /// <summary>
            /// The SomeBodyTag item info.
            /// </summary>
            [RepositoryItemInfo("53261d83-8c87-4b05-8546-89b805b825d8")]
            public virtual RepoItemInfo SomeBodyTagInfo
            {
                get
                {
                    return _somebodytagInfo;
                }
            }

            /// <summary>
            /// The Calendar item.
            /// </summary>
            [RepositoryItem("9ef39c80-0c5c-4f2c-bbd9-6083679df5a0")]
            public virtual Ranorex.ButtonTag Calendar
            {
                get
                {
                    return _calendarInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The Calendar item info.
            /// </summary>
            [RepositoryItemInfo("9ef39c80-0c5c-4f2c-bbd9-6083679df5a0")]
            public virtual RepoItemInfo CalendarInfo
            {
                get
                {
                    return _calendarInfo;
                }
            }

            /// <summary>
            /// The ThuApr13th2017 item.
            /// </summary>
            [RepositoryItem("beb20ba8-fc45-40c6-8f99-14c305b2c013")]
            public virtual Ranorex.TdTag ThuApr13th2017
            {
                get
                {
                    return _thuapr13th2017Info.CreateAdapter<Ranorex.TdTag>(true);
                }
            }

            /// <summary>
            /// The ThuApr13th2017 item info.
            /// </summary>
            [RepositoryItemInfo("beb20ba8-fc45-40c6-8f99-14c305b2c013")]
            public virtual RepoItemInfo ThuApr13th2017Info
            {
                get
                {
                    return _thuapr13th2017Info;
                }
            }

            /// <summary>
            /// The Blue item.
            /// </summary>
            [RepositoryItem("f3657d7f-2e18-4e1d-a99e-e89418632647")]
            public virtual Ranorex.OptionTag Blue
            {
                get
                {
                    return _blueInfo.CreateAdapter<Ranorex.OptionTag>(true);
                }
            }

            /// <summary>
            /// The Blue item info.
            /// </summary>
            [RepositoryItemInfo("f3657d7f-2e18-4e1d-a99e-e89418632647")]
            public virtual RepoItemInfo BlueInfo
            {
                get
                {
                    return _blueInfo;
                }
            }

            /// <summary>
            /// The Testmultiple item.
            /// </summary>
            [RepositoryItem("1fb7c4e1-48a2-44ee-8e82-ae643da4f873")]
            public virtual Ranorex.SelectTag Testmultiple
            {
                get
                {
                    return _testmultipleInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The Testmultiple item info.
            /// </summary>
            [RepositoryItemInfo("1fb7c4e1-48a2-44ee-8e82-ae643da4f873")]
            public virtual RepoItemInfo TestmultipleInfo
            {
                get
                {
                    return _testmultipleInfo;
                }
            }

            /// <summary>
            /// The OptionTagRed item.
            /// </summary>
            [RepositoryItem("2546f8cf-8984-4493-a168-a51311f3902c")]
            public virtual Ranorex.OptionTag OptionTagRed
            {
                get
                {
                    return _optiontagredInfo.CreateAdapter<Ranorex.OptionTag>(true);
                }
            }

            /// <summary>
            /// The OptionTagRed item info.
            /// </summary>
            [RepositoryItemInfo("2546f8cf-8984-4493-a168-a51311f3902c")]
            public virtual RepoItemInfo OptionTagRedInfo
            {
                get
                {
                    return _optiontagredInfo;
                }
            }

            /// <summary>
            /// The Gray item.
            /// </summary>
            [RepositoryItem("552323d2-146f-4ea5-8041-767126f63bdc")]
            public virtual Ranorex.OptionTag Gray
            {
                get
                {
                    return _grayInfo.CreateAdapter<Ranorex.OptionTag>(true);
                }
            }

            /// <summary>
            /// The Gray item info.
            /// </summary>
            [RepositoryItemInfo("552323d2-146f-4ea5-8041-767126f63bdc")]
            public virtual RepoItemInfo GrayInfo
            {
                get
                {
                    return _grayInfo;
                }
            }

            /// <summary>
            /// The Submit item.
            /// </summary>
            [RepositoryItem("32c9a657-0172-44ee-87e8-6af62dca8ebb")]
            public virtual Ranorex.InputTag Submit
            {
                get
                {
                    return _submitInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Submit item info.
            /// </summary>
            [RepositoryItemInfo("32c9a657-0172-44ee-87e8-6af62dca8ebb")]
            public virtual RepoItemInfo SubmitInfo
            {
                get
                {
                    return _submitInfo;
                }
            }

            /// <summary>
            /// The ArrayTestnameEqUserName item.
            /// </summary>
            [RepositoryItem("1763f1f6-1a6e-42e0-830f-36d111ebbee4")]
            public virtual Ranorex.PreTag ArrayTestnameEqUserName
            {
                get
                {
                    return _arraytestnameequsernameInfo.CreateAdapter<Ranorex.PreTag>(true);
                }
            }

            /// <summary>
            /// The ArrayTestnameEqUserName item info.
            /// </summary>
            [RepositoryItemInfo("1763f1f6-1a6e-42e0-830f-36d111ebbee4")]
            public virtual RepoItemInfo ArrayTestnameEqUserNameInfo
            {
                get
                {
                    return _arraytestnameequsernameInfo;
                }
            }

            /// <summary>
            /// The Green item.
            /// </summary>
            [RepositoryItem("0f1eb2c6-a31d-43cc-bc1f-6123f60cc674")]
            public virtual Ranorex.OptionTag Green
            {
                get
                {
                    return _greenInfo.CreateAdapter<Ranorex.OptionTag>(true);
                }
            }

            /// <summary>
            /// The Green item info.
            /// </summary>
            [RepositoryItemInfo("0f1eb2c6-a31d-43cc-bc1f-6123f60cc674")]
            public virtual RepoItemInfo GreenInfo
            {
                get
                {
                    return _greenInfo;
                }
            }

            /// <summary>
            /// The Testdate item.
            /// </summary>
            [RepositoryItem("baea20b2-f16d-4ae6-a57e-4905cd89aecb")]
            public virtual Ranorex.InputTag Testdate
            {
                get
                {
                    return _testdateInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Testdate item info.
            /// </summary>
            [RepositoryItemInfo("baea20b2-f16d-4ae6-a57e-4905cd89aecb")]
            public virtual RepoItemInfo TestdateInfo
            {
                get
                {
                    return _testdateInfo;
                }
            }

            /// <summary>
            /// The Value1 item.
            /// </summary>
            [RepositoryItem("c07fc419-d765-48f0-95a3-75bab194f444")]
            public virtual Ranorex.InputTag Value1
            {
                get
                {
                    return _value1Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Value1 item info.
            /// </summary>
            [RepositoryItemInfo("c07fc419-d765-48f0-95a3-75bab194f444")]
            public virtual RepoItemInfo Value1Info
            {
                get
                {
                    return _value1Info;
                }
            }

            /// <summary>
            /// The Value2 item.
            /// </summary>
            [RepositoryItem("9609b147-5f7d-4ea0-b3e2-fa14e69f8d04")]
            public virtual Ranorex.InputTag Value2
            {
                get
                {
                    return _value2Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Value2 item info.
            /// </summary>
            [RepositoryItemInfo("9609b147-5f7d-4ea0-b3e2-fa14e69f8d04")]
            public virtual RepoItemInfo Value2Info
            {
                get
                {
                    return _value2Info;
                }
            }

            /// <summary>
            /// The SubmitAjax item.
            /// </summary>
            [RepositoryItem("754638dc-0bc4-41cd-8021-c2808f9ff537")]
            public virtual Ranorex.InputTag SubmitAjax
            {
                get
                {
                    return _submitajaxInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The SubmitAjax item info.
            /// </summary>
            [RepositoryItemInfo("754638dc-0bc4-41cd-8021-c2808f9ff537")]
            public virtual RepoItemInfo SubmitAjaxInfo
            {
                get
                {
                    return _submitajaxInfo;
                }
            }

            /// <summary>
            /// The AjaxOut item.
            /// </summary>
            [RepositoryItem("f889e3d0-b7a2-4667-b743-5464c457b30a")]
            public virtual Ranorex.DivTag AjaxOut
            {
                get
                {
                    return _ajaxoutInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The AjaxOut item info.
            /// </summary>
            [RepositoryItemInfo("f889e3d0-b7a2-4667-b743-5464c457b30a")]
            public virtual RepoItemInfo AjaxOutInfo
            {
                get
                {
                    return _ajaxoutInfo;
                }
            }

            /// <summary>
            /// The Testform item.
            /// </summary>
            [RepositoryItem("33e1ee9f-2da8-462e-bf63-85e4efa69759")]
            public virtual Ranorex.FormTag Testform
            {
                get
                {
                    return _testformInfo.CreateAdapter<Ranorex.FormTag>(true);
                }
            }

            /// <summary>
            /// The Testform item info.
            /// </summary>
            [RepositoryItemInfo("33e1ee9f-2da8-462e-bf63-85e4efa69759")]
            public virtual RepoItemInfo TestformInfo
            {
                get
                {
                    return _testformInfo;
                }
            }

            /// <summary>
            /// The ArrayValue1Eq1Value2E1 item.
            /// </summary>
            [RepositoryItem("c90bb30e-4c26-4420-ab27-b90608704770")]
            public virtual Ranorex.PreTag ArrayValue1Eq1Value2E1
            {
                get
                {
                    return _arrayvalue1eq1value2e1Info.CreateAdapter<Ranorex.PreTag>(true);
                }
            }

            /// <summary>
            /// The ArrayValue1Eq1Value2E1 item info.
            /// </summary>
            [RepositoryItemInfo("c90bb30e-4c26-4420-ab27-b90608704770")]
            public virtual RepoItemInfo ArrayValue1Eq1Value2E1Info
            {
                get
                {
                    return _arrayvalue1eq1value2e1Info;
                }
            }

            /// <summary>
            /// The ArrayValue1Eq1Value2E item.
            /// </summary>
            [RepositoryItem("8582ee05-09da-45e8-86e5-7489a314bedf")]
            public virtual Ranorex.PreTag ArrayValue1Eq1Value2E
            {
                get
                {
                    return _arrayvalue1eq1value2eInfo.CreateAdapter<Ranorex.PreTag>(true);
                }
            }

            /// <summary>
            /// The ArrayValue1Eq1Value2E item info.
            /// </summary>
            [RepositoryItemInfo("8582ee05-09da-45e8-86e5-7489a314bedf")]
            public virtual RepoItemInfo ArrayValue1Eq1Value2EInfo
            {
                get
                {
                    return _arrayvalue1eq1value2eInfo;
                }
            }
        }

        /// <summary>
        /// The WwwRanorexComWebTestingExamplesForAppFolder folder.
        /// </summary>
        [RepositoryFolder("37a0fe02-ff1b-45fb-8521-e27c972e818b")]
        public partial class WwwRanorexComWebTestingExamplesForAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _intermediated3dwindowInfo;

            /// <summary>
            /// Creates a new WwwRanorexComWebTestingExamplesFor  folder.
            /// </summary>
            public WwwRanorexComWebTestingExamplesForAppFolder(RepoGenBaseFolder parentFolder) :
                    base("WwwRanorexComWebTestingExamplesFor", "/form[@title~'^www\\.ranorex\\.com/web-testi']", parentFolder, 30000, null, true, "37a0fe02-ff1b-45fb-8521-e27c972e818b", "")
            {
                _intermediated3dwindowInfo = new RepoItemInfo(this, "IntermediateD3DWindow", "element[@class='Intermediate D3D Window']", 30000, null, "ece8756f-fc70-48f1-955e-600552d46683");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("37a0fe02-ff1b-45fb-8521-e27c972e818b")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("37a0fe02-ff1b-45fb-8521-e27c972e818b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The IntermediateD3DWindow item.
            /// </summary>
            [RepositoryItem("ece8756f-fc70-48f1-955e-600552d46683")]
            public virtual Ranorex.Unknown IntermediateD3DWindow
            {
                get
                {
                    return _intermediated3dwindowInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The IntermediateD3DWindow item info.
            /// </summary>
            [RepositoryItemInfo("ece8756f-fc70-48f1-955e-600552d46683")]
            public virtual RepoItemInfo IntermediateD3DWindowInfo
            {
                get
                {
                    return _intermediated3dwindowInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}